# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"

stages:
  - build
  - deploy

documentation:
  tags:
    - debian, docker
  stage: build
  variables:
    DOCKER_AUTH_CONFIG: "${DOCKER_AUTH_CONFIG_SPHINX}"
  image:
    name: ${CI_REGISTRY}/internal/docker-sphinx:latest
  script:
    - cd docu/doxygen
    - doxygen
    - cp -r xml ../sphinx/source
    - cd ../sphinx
    - make html
  artifacts:
    paths:
      - docu/sphinx/build/html

testing:
  stage: build
  tags:
    - debian, docker
  parallel:
    matrix:
      - IGOR_VERSION: [6, 7, 8, 9]
  variables:
    DOCKER_AUTH_CONFIG: "${DOCKER_AUTH_CONFIG_IGOR_PRO}"
  image:
    name: ${CI_REGISTRY}/internal/docker-igorpro:v${IGOR_VERSION}
  script:
    - ln -rs procedures "/home/igor/WaveMetrics/Igor Pro ${IGOR_VERSION} User Files/User Procedures/utf"
    - ln -rs tests "/home/igor/WaveMetrics/Igor Pro ${IGOR_VERSION} User Files/User Procedures/tests"
    - touch tests/DO_AUTORUN.TXT
    - igorpro execute --verbose --screenshot "tests/VeryTinyTestEnvironment.pxp"
    - exit $(grep -e "errors=\"[0-9]\+\"" -e "failures=\"[0-9]\+\"" tests/JU_*.xml | grep -cv "failures=\"0\" errors=\"0\"")
  artifacts:
    when: always
    reports:
      junit: tests/JU_*.xml
    paths:
      - tests/JU_*.xml
      - screenshot/*.png

deployment_staging:
  when: manual
  tags:
    - debian, docker
  stage: deploy
  image:
    name: ${CI_REGISTRY}/internal/docker-utils:latest
  variables:
    DOCKER_AUTH_CONFIG: "${DOCKER_AUTH_CONFIG_UTILS}"
  script:
    - cd docu/sphinx
    - lftp -e "mirror --reverse -n -e build/html /igor-unit-testing-framework; bye" -u $FTP_USER_DOCS_STAGING,$FTP_PW_DOCS_STAGING byte-physics.de
  needs:
    - documentation

deployment:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$SCHEDULER_TYPE'
      when: never
  tags:
    - debian, docker
  stage: deploy
  image:
    name: ${CI_REGISTRY}/internal/docker-utils:latest
  variables:
    DOCKER_AUTH_CONFIG: "${DOCKER_AUTH_CONFIG_UTILS}"
  script:
    - cd docu/sphinx
    - lftp -e "mirror --reverse -n -e build/html /igor-unit-testing-framework; bye" -u $FTP_USER_DOCS,$FTP_PW_DOCS byte-physics.de
  needs:
    - documentation
    - job: testing
      artifacts: false
